# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = src/Book/add_book.o src/Book/book.o src/Book/display_book.o src/Book/search_book.o src/Book/search_book_isbn.o src/Hardware/add_hardware.o src/Hardware/display_hardware.o src/Hardware/Filter_Hardware_with_OS.o src/Hardware/Filter_Hardware_with_RAM.o src/Hardware/Filter_Hardware_with_ROM.o src/Hardware/Filter_Hardware_with_type.o src/Hardware/hardware.o src/Hardware/Search_hardware_by_name.o src/main.o src/Software/add_software.o src/Software/display_software.o src/Software/Filter_Software_with_OS.o src/Software/Search_Software_by_name.o src/Software/software.o
LINKOBJ  = src/Book/add_book.o src/Book/book.o src/Book/display_book.o src/Book/search_book.o src/Book/search_book_isbn.o src/Hardware/add_hardware.o src/Hardware/display_hardware.o src/Hardware/Filter_Hardware_with_OS.o src/Hardware/Filter_Hardware_with_RAM.o src/Hardware/Filter_Hardware_with_ROM.o src/Hardware/Filter_Hardware_with_type.o src/Hardware/hardware.o src/Hardware/Search_hardware_by_name.o src/main.o src/Software/add_software.o src/Software/display_software.o src/Software/Filter_Software_with_OS.o src/Software/Search_Software_by_name.o src/Software/software.o
LIBS     = -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib" -L"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"C:/Program Files (x86)/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = Project1.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o $(BIN) $(LIBS)

src/Book/add_book.o: src/Book/add_book.c
	$(CC) -c src/Book/add_book.c -o src/Book/add_book.o $(CFLAGS)

src/Book/book.o: src/Book/book.c
	$(CC) -c src/Book/book.c -o src/Book/book.o $(CFLAGS)

src/Book/display_book.o: src/Book/display_book.c
	$(CC) -c src/Book/display_book.c -o src/Book/display_book.o $(CFLAGS)

src/Book/search_book.o: src/Book/search_book.c
	$(CC) -c src/Book/search_book.c -o src/Book/search_book.o $(CFLAGS)

src/Book/search_book_isbn.o: src/Book/search_book_isbn.c
	$(CC) -c src/Book/search_book_isbn.c -o src/Book/search_book_isbn.o $(CFLAGS)

src/Hardware/add_hardware.o: src/Hardware/add_hardware.c
	$(CC) -c src/Hardware/add_hardware.c -o src/Hardware/add_hardware.o $(CFLAGS)

src/Hardware/display_hardware.o: src/Hardware/display_hardware.c
	$(CC) -c src/Hardware/display_hardware.c -o src/Hardware/display_hardware.o $(CFLAGS)

src/Hardware/Filter_Hardware_with_OS.o: src/Hardware/Filter_Hardware_with_OS.c
	$(CC) -c src/Hardware/Filter_Hardware_with_OS.c -o src/Hardware/Filter_Hardware_with_OS.o $(CFLAGS)

src/Hardware/Filter_Hardware_with_RAM.o: src/Hardware/Filter_Hardware_with_RAM.c
	$(CC) -c src/Hardware/Filter_Hardware_with_RAM.c -o src/Hardware/Filter_Hardware_with_RAM.o $(CFLAGS)

src/Hardware/Filter_Hardware_with_ROM.o: src/Hardware/Filter_Hardware_with_ROM.c
	$(CC) -c src/Hardware/Filter_Hardware_with_ROM.c -o src/Hardware/Filter_Hardware_with_ROM.o $(CFLAGS)

src/Hardware/Filter_Hardware_with_type.o: src/Hardware/Filter_Hardware_with_type.c
	$(CC) -c src/Hardware/Filter_Hardware_with_type.c -o src/Hardware/Filter_Hardware_with_type.o $(CFLAGS)

src/Hardware/hardware.o: src/Hardware/hardware.c
	$(CC) -c src/Hardware/hardware.c -o src/Hardware/hardware.o $(CFLAGS)

src/Hardware/Search_hardware_by_name.o: src/Hardware/Search_hardware_by_name.c
	$(CC) -c src/Hardware/Search_hardware_by_name.c -o src/Hardware/Search_hardware_by_name.o $(CFLAGS)

src/main.o: src/main.c
	$(CC) -c src/main.c -o src/main.o $(CFLAGS)

src/Software/add_software.o: src/Software/add_software.c
	$(CC) -c src/Software/add_software.c -o src/Software/add_software.o $(CFLAGS)

src/Software/display_software.o: src/Software/display_software.c
	$(CC) -c src/Software/display_software.c -o src/Software/display_software.o $(CFLAGS)

src/Software/Filter_Software_with_OS.o: src/Software/Filter_Software_with_OS.c
	$(CC) -c src/Software/Filter_Software_with_OS.c -o src/Software/Filter_Software_with_OS.o $(CFLAGS)

src/Software/Search_Software_by_name.o: src/Software/Search_Software_by_name.c
	$(CC) -c src/Software/Search_Software_by_name.c -o src/Software/Search_Software_by_name.o $(CFLAGS)

src/Software/software.o: src/Software/software.c
	$(CC) -c src/Software/software.c -o src/Software/software.o $(CFLAGS)
